import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "./globals.css";

const sarabun = Sarabun({
    weight: ["400", "700"],
    subsets: ["thai", "latin"],
    variable: "--font-sarabun",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="th">
            <body className={`${sarabun.variable} font-sans antialiased`}>
                {children}
            </body>
        </html>
    );
}
